steps:
  - label: ":python: Generate the pipeline"
    commands:
      - sudo apt update && sudo apt install -y bazelisk
      - "bazel run //pipeline:main --ui_event_filters=-INFO --noshow_progress --show_result=0 | buildkite-agent pipeline upload"
