steps:
  - label: ":python: Generate the pipeline"
    commands:
      - wget https://github.com/bazelbuild/bazelisk/releases/download/v1.25.0/bazelisk-amd64.deb && sudo dpkg -i bazelisk-amd64.deb
      - "bazel run //pipeline:main --ui_event_filters=-INFO --noshow_progress --show_result=0 | buildkite-agent pipeline upload"
